ktor:
  application:
    modules:
      - com.transfair.ApplicationKt.module
  deployment:
    port: 8080

storage:
  type: local
  expiration: 604800 # Expiration in seconds

database:
  type: sqlite
  url: jdbc:sqlite:data/tranfair.db
  fileName: tranfair.db

